CREATE TABLE [TBLDECLARATION] (
  [DecNumero] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [DecDateCreation] DATETIME,
  [DecDateModification] DATETIME,
  [DecDate] DATETIME,
  [DecTypDecNumero] LONG,
  [DecDeclarantEntNumero] LONG,
  [DecDeclarantNom] VARCHAR (50),
  [DecDeclarantPrenom] VARCHAR (50),
  [DecDeclarantQualite] VARCHAR (50),
  [DecDeclarantTelephone1] VARCHAR (10),
  [DecDeclarantTelephone2] VARCHAR (10),
  [DecDeclarantMail] VARCHAR (150),
  [DecVictimeNom] VARCHAR (50),
  [DecVictimePrenom] VARCHAR (50),
  [DecVictimeNaissanceDate] DATETIME,
  [DecVictimeNaissanceLieu] VARCHAR (50),
  [DecVictimeAdresse] VARCHAR (200),
  [DecVictimeCodePostal] VARCHAR (5),
  [DecVictimeVille] VARCHAR (50),
  [DecVictimePays] VARCHAR (50),
  [DecVictimeTelephone1] VARCHAR (10),
  [DecVictimeTelephone2] VARCHAR (10),
  [DecVictimeRIB] VARCHAR (30),
  [DecVictimeTypCptNumero] LONG,
  [DecVictimeAgence] VARCHAR (50),
  [DecVictimeAgenceAdresse] VARCHAR (200),
  [DecVictimeAgenceCodePostal] VARCHAR (5),
  [DecVictimeAgenceVille] VARCHAR (50),
  [DecVictimeAgencePays] VARCHAR (50),
  [DecVictimeMarNumero] LONG,
  [DecBeneficiaireTypBenNumero] LONG,
  [DecBeneficiaireNom] VARCHAR (50),
  [DecBeneficiairePrenom] VARCHAR (50),
  [DecBeneficiaireNaissanceDate] DATETIME,
  [DecBeneficiaireNaissanceLieu] VARCHAR (50),
  [DecBeneficiaireAdresse] VARCHAR (200),
  [DecBeneficiaireCodePostal] VARCHAR (5),
  [DecBeneficiaireVille] VARCHAR (50),
  [DecBeneficiairePays] VARCHAR (50),
  [DecBeneficiaireTelephone1] VARCHAR (10),
  [DecBeneficiaireTelephone2] VARCHAR (10),
  [DecBeneficiaireRIB] VARCHAR (30),
  [DecBeneficiaireBanque] VARCHAR (50),
  [DecBeneficiaireAgence] VARCHAR (50),
  [DecBeneficiaireAgenceAdresse] VARCHAR (200),
  [DecBeneficiaireAgenceCodePostal] VARCHAR (5),
  [DecBeneficiaireAgenceVille] VARCHAR (50),
  [DecBeneficiaireAgencePays] VARCHAR (50),
  [DecBeneficiaireAgenceAppel] BIT,
  [DecBeneficiaireAgenceResponsableNom] VARCHAR (50),
  [DecBeneficiaireAgenceResponsablePrenom] VARCHAR (50),
  [DecBeneficiaireAgenceResponsableTelephone1] VARCHAR (10),
  [DecBeneficiaireAgenceResponsableTelephone2] VARCHAR (10),
  [DecBeneficiaireCommentaire] LONGTEXT,
  [DecFraudeDate] DATETIME,
  [DecFraudeHeure] DATETIME,
  [DecFraudeTypOpeNumero] LONG,
  [DecFraudeMontant] CURRENCY,
  [DecFraudeMontantRecuperer] CURRENCY,
  [DecFraudeLibelle] VARCHAR (50),
  [DecFraudeTypFrdNumero] LONG,
  [DecFraudeSouIPNumero] LONG,
  [DecFraudeAdresseIP] VARCHAR (15),
  [DecFraudeDecaissementDate] DATETIME,
  [DecFraudeDecaissementHeure] DATETIME,
  [DecFraudeDecaissementMontant] CURRENCY,
  [DecFraudeCommentaire] LONGTEXT,
  [DecDepotPlainteClient] BIT,
  [DecDepotPlainteClientDate] DATETIME,
  [DecDepotPlainteClientAutNumero] LONG,
  [DecDepotPlainteClientLieu] VARCHAR (250),
  [DecDepotPlainteClientAccepter] BIT,
  [DecDepotPlainteClientMotif] VARCHAR (250),
  [DecDepotPlainteEntite] BIT,
  [DecDepotPlainteEntiteDate] DATETIME,
  [DecDepotPlainteEntiteAutNumero] LONG,
  [DecDepotPlainteEntiteLieu] VARCHAR (250),
  [DecDepotPlainteEntiteAccepter] BIT,
  [DecDepotPlainteEntiteMotif] VARCHAR (250),
  [DecSiteIlliciteDate] DATETIME,
  [DecSiteIlliciteStaSitNumero] LONG,
  [DecSiteIlliciteSouSitNumero] LONG,
  [DecSiteIlliciteURLAdresse] VARCHAR (200),
  [DecSiteIlliciteLocSitNumero] LONG,
  [DecSiteIlliciteHebergeur] VARCHAR (50),
  [DecSiteIlliciteHebergeurAdresse] VARCHAR (200),
  [DecSiteIlliciteHebergeurCodePostal] VARCHAR (5),
  [DecSiteIlliciteHebergeurVille] VARCHAR (50),
  [DecSiteIlliciteHebergeurPays] VARCHAR (50),
  [DecSiteIlliciteSuivi] LONGTEXT,
  [DecSiteIlliciteCommentaire] LONGTEXT,
  [DecLiaisonSFDate] DATETIME,
  [DecLiaisonSFRetour] LONGTEXT
)
