CREATE TABLE [TBLENTITE] (
  [EntNumero] AUTOINCREMENT CONSTRAINT [CleEntNumero] UNIQUE,
  [EntCode] LONG CONSTRAINT [CleEntCode] UNIQUE,
  [EntNom] VARCHAR (50) CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL
)
